services:
#  gym-management-app:
#    build: .
#    container_name: gym-management
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/abcfitness
#      SPRING_DATASOURCE_USERNAME: AbcFitness
#      SPRING_DATASOURCE_PASSWORD: Admin#123
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    depends_on:
#      - postgres

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=abcfitness'
      - 'POSTGRES_PASSWORD=Admin#123'
      - 'POSTGRES_USER=AbcFitness'
    ports:
      - '5432'