version: '3.8'

services:
  gym-management-app:
    container_name: gym-management
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/abcfitness
      SPRING_DATASOURCE_USERNAME: AbcFitness
      SPRING_DATASOURCE_PASSWORD: Admin#123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    container_name: gym-management-db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=abcfitness'
      - 'POSTGRES_PASSWORD=Admin#123'
      - 'POSTGRES_USER=AbcFitness'
    restart: always
    ports:
      - "5432:5432"